# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: unodos_development
  pool: 5

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: unodos_test
  pool: 5
